### ISSUE TITLE
vit10分类实验

### ISSUE THREAD

**Issue by Yuichi1001** [dxcf123/UCAS_DeepLearning_homework#1]
用仓库里的代码自己跑了400个epoch后准确率只到0.77左右 请问最后您是在哪些地方又做了修改么

**Comment by dxcf123** [comment]
那只是一个demo，一个从0构建VIT的demo，结果是以前跑的，完整的网络我的电脑运行不了，你要增加准确率，要么增加网络参数，要么增强数据。
我再给你个demo，用的助教的代码，不过我也简化了，否则运行不了，准确率我只跑到了85，网络还是太小了。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dxcf123/UCAS_DeepLearning_homework"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月14日(星期二) 凌晨0:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[dxcf123/UCAS_DeepLearning_homework] vit10分类实验 (Issue #1)





 
用仓库里的代码自己跑了400个epoch后准确率只到0.77左右 请问最后您是在哪些地方又做了修改么

**Comment by dxcf123** [comment]
上个文件的学习率和Encoder的层数可以加一加




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dxcf123/UCAS_DeepLearning_homework"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月14日(星期二) 凌晨0:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[dxcf123/UCAS_DeepLearning_homework] vit10分类实验 (Issue #1)





 
用仓库里的代码自己跑了400个epoch后准确率只到0.77左右 请问最后您是在哪些地方又做了修改么

**Comment by Yuichi1001** [comment]
我这里看不到你新发的demo 但还是感谢 我再改改代码

**Comment by dxcf123** [comment]
我发的邮件附件








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年5月14日(周二) 晚上6:13写道:

  

 
我这里看不到你新发的demo 但还是感谢 我再改改代码

**Comment by Yuichi1001** [comment]
您回复我是发到GitHub那边 然后他那边再转发一次 所以我看不到附件 ***@***.***&nbsp; 能麻烦您再发一次么



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月14日(周二) 晚上6:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [dxcf123/UCAS_DeepLearning_homework] vit10分类实验 (Issue #1)




 我发的邮件附件 
 
 
 
 
 
 
 
 
  ----------回复的邮件信息---------- 
  ***@***.***&amp;gt; 于2024年5月14日(周二) 晚上6:13写道: 
 
    
 
   
 我这里看不到你新发的demo 但还是感谢 我再改改代码

**Comment by dxcf123** [comment]
我马上更新到github仓库里




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dxcf123/UCAS_DeepLearning_homework"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月14日(星期二) 晚上6:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dxcf123/UCAS_DeepLearning_homework] vit10分类实验 (Issue #1)





 
我这里看不到你新发的demo 但还是感谢 我再改改代码

**Comment by dxcf123** [comment]
我上传了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dxcf123/UCAS_DeepLearning_homework"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月14日(星期二) 晚上6:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dxcf123/UCAS_DeepLearning_homework] vit10分类实验 (Issue #1)





 您回复我是发到GitHub那边 然后他那边再转发一次 所以我看不到附件 ***@***.***&amp;nbsp; 能麻烦您再发一次么 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2024年5月14日(周二) 晚上6:14 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题: Re: [dxcf123/UCAS_DeepLearning_homework] vit10分类实验 (Issue #1) 
 
 
 
 
  我发的邮件附件  
   
   
   
   
   
   
   
   
   ----------回复的邮件信息----------  
   ***@***.***&amp;amp;gt; 于2024年5月14日(周二) 晚上6:13写道:  
   
      
   
     
  我这里看不到你新发的demo 但还是感谢 我再改改代码

**Comment by Yuichi1001** [comment]
好的 感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月14日(周二) 晚上6:22
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [dxcf123/UCAS_DeepLearning_homework] vit10分类实验 (Issue #1)




 我上传了 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "dxcf123/UCAS_DeepLearning_homework"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年5月14日(星期二) 晚上6:17 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [dxcf123/UCAS_DeepLearning_homework] vit10分类实验 (Issue #1) 
 
 
 
 
 
  您回复我是发到GitHub那边 然后他那边再转发一次 所以我看不到附件 ***@***.***&amp;amp;nbsp; 能麻烦您再发一次么  
   
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2024年5月14日(周二) 晚上6:14  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.***&amp;amp;gt;;"State ***@***.***&amp;amp;gt;;  
  主题: Re: [dxcf123/UCAS_DeepLearning_homework] vit10分类实验 (Issue #1)  
   
   
   
   
   我发的邮件附件   
     
     
     
     
     
     
     
     
    ----------回复的邮件信息----------   
    ***@***.***&amp;amp;amp;gt; 于2024年5月14日(周二) 晚上6:13写道:   
     
        
     
       
   我这里看不到你新发的demo 但还是感谢 我再改改代码

**Comment by ywlywl6** [comment]
那作者你也只跑到了85吗，90精度感觉确实离谱。我的规模挺大了，跑了一晚上过拟合了没上80

**Comment by dxcf123** [comment]
我电脑最高跑到87




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dxcf123/UCAS_DeepLearning_homework"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月15日(星期三) 上午10:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dxcf123/UCAS_DeepLearning_homework] vit10分类实验 (Issue #1)





 
那作者你也只跑到了85吗，90精度感觉确实离谱。我的规模挺大了，跑了一晚上过拟合了没上80

**Comment by Yuichi1001** [comment]
好像自己搞确实不好上90 要在预训练模型的基础上微调 不过听说有的班把90%的精度下调到80%了

**Comment by Yuichi1001** [comment]
> 那作者你也只跑到了85吗，90精度感觉确实离谱。我的规模挺大了，跑了一晚上过拟合了没上80

像自己搞确实不好上90 要在预训练模型的基础上微调 不过听说有的班把90%的精度下调到80%了
