### ISSUE TITLE
机器翻译的optimizer

### ISSUE THREAD

**Issue by zhaozhaoooo** [dxcf123/UCAS_DeepLearning_homework#2]
嗨同学，你自己从零训练的那个文件里optimizer是默认的吗？因为我用那个训练一直不收敛，最后的损失函数还是2点多，最后训练的100个epoch也没有BLEU达到14以上的
![屏幕截图 2024-05-29 145614](https://github.com/dxcf123/UCAS_DeepLearning_homework/assets/149659360/c3d576ac-8ecb-41c1-a0fe-a593043ace3d)

**Comment by dxcf123** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dxcf123/UCAS_DeepLearning_homework"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月29日(星期三) 下午2:57
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[dxcf123/UCAS_DeepLearning_homework] 机器翻译的optimizer (Issue #2)





 
嗨同学，你自己从零训练的那个文件里optimizer是默认的吗？因为我用那个训练一直不收敛，最后的损失函数还是2点多，最后训练的100个epoch也没有BLEU达到14以上的
 2024-05-29.145614.png (view on web)

**Comment by dxcf123** [comment]
你训练和测试要用相同的tokenizer，就是tokenizer建一次就不要动了，我25个epoch就达到了啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dxcf123/UCAS_DeepLearning_homework"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月29日(星期三) 下午2:57
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[dxcf123/UCAS_DeepLearning_homework] 机器翻译的optimizer (Issue #2)





 
嗨同学，你自己从零训练的那个文件里optimizer是默认的吗？因为我用那个训练一直不收敛，最后的损失函数还是2点多，最后训练的100个epoch也没有BLEU达到14以上的
 2024-05-29.145614.png (view on web)
